### ISSUE TITLE
Need to Add page in nsis installer

### ISSUE THREAD

**Issue by SivaThiyagarajan** [nmoinvaz/nsis-base64#1]
Actually i just used electron builder (nsis target) to create a setup file for windows application, but i need to add another one installer page in the setup, so i can get the input (serverIP) from the end user and i can modify the api_url in app.asar file or asar unpacked main.js file. Is there is any another way? I checked the Custom Installer script, but it is little confusing. So Please help me in this. And Thanks in advance.

**Comment by nmoinvaz** [comment]
I am not sure what you are talking about.
